### ISSUE TITLE
You have links of the data

### ISSUE THREAD

**Issue by NaziYeeter** [abc64/PunishingGrayRavenData#1]
They already blocked it so i cant hook datas
If you can share much appreciated 
I just wanna make website for items and characters

**Comment by abc64** [comment]
Hi,

I'll try to update the repo as soon as possible.

**Comment by NaziYeeter** [comment]
Thanks

**Comment by abc64** [comment]
I have updated the repo to the latest version I found. If there's any other issues, feel free to open another issue.
